### ISSUE TITLE
cloudera enterprise 평가판 만료

### ISSUE THREAD

**Issue by jay-eon** [wikibook/bigdata2nd#17]
바뀐대로 vmware 이미지를 다운받아서 실행해도 cloudera에서 사용할수 있는 버전이 없습니다.. 무료버전이나 기업 라이센스버전밖에 없어 실행할 수가 없습니다.

**Comment by wikibook** [comment]
안녕하세요! 김강원입니다.

책의 실습에선 Enterprise 기능을 사용하지 않기 때문에, 

Cloudera Express 무료 라이선스 버전을 선택해 사용하시면 됩니다. 

참고로 Enterprise 기능은 보안 및 관리자 기능 등이 제공됩니다.
