### ISSUE TITLE
Cloudera 버전이 만료되었습니다. 무료버전으로만 진행이 되지 않습니다

### ISSUE THREAD

**Issue by jay-eon** [wikibook/bigdata2nd#18]
안녕하세요, 이책으로 실습을 진행중인데 책 구매 후 실습에 문제가 있어
github에 문의 올립니다.

수정부분을 참고하여 google download를 통해 VM이미지를 다운받아 실습을 진행하려고 했지만,
cloudera 설치 진행 초반에 60일 테스트가 만료되어 무료버전으로밖에 진행이 안되는 경우가 발생하였습니다.

실습이 무료버전으로 진행하여도 문제가 없는지 문의드리기 위해 남깁니다.
도움 주시면 감사하겠습니다,

**Comment by wikibook** [comment]
@jay-eon 님, 안녕하세요. 위키북스 담당자입니다.

수정된 부분을 참고하셔서 다운로드하신 VM 이미지로 실습을 진행하신다면 무료버전으로 진행하셔도 됩니다.

추후 실습 과정에서 문제가 있으시면 번거로우시겠지만 다시 알려주시면 감사하겠습니다.
그럼 좋은 하루 보내세요.
감사합니다.
